In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

from utils import imp
import importlib
importlib.reload(imp)

import joblib

In [2]:
df = pd.DataFrame(
    data={
        'PAYMENTS': [np.nan, 100, np.nan],
        'MINIMUM_PAYMENTS': [100, 100, 100],
        'AGE': [50,np.nan,60]
    }
)

In [3]:
c1 = Pipeline(
    steps=[
        ('imputer', FunctionTransformer(func=imp.imp1, kw_args={'features': df.columns}, feature_names_out=imp.imp1_out))
        # ('imputer', SimpleImputer(strategy='median'))
    ]
)

c2 = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median'))
    ]
)

com = ColumnTransformer(
    transformers=[
        ('c1', c1, ['PAYMENTS', 'MINIMUM_PAYMENTS']),
        ('c2', c2, ['AGE'])
    ]
)

print(df)

print(com.fit_transform(X=df), com.get_feature_names_out())

with open('./deployment/pipe.pkl', 'wb') as file_1:
    joblib.dump(value=c1, filename=file_1)

   PAYMENTS  MINIMUM_PAYMENTS   AGE
0       NaN               100  50.0
1     100.0               100   NaN
2       NaN               100  60.0
[[100. 100.  50.]
 [100. 100.  55.]
 [100. 100.  60.]] ['c1__PAYMENTS' 'c1__MINIMUM_PAYMENTS' 'c1__AGE' 'c2__AGE']
