In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('./dataset/wine_fraud.csv')

In [4]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol quality   type  
0         9.4   Legit    red  
1         9.8   Legit    red  
2         9.8   Legit    red  
3         9.8   Legit    red  
4         9.4   Legit    red  
...       ...     ...    ...  
6492     11.2   Legit  white  
6493      9.6   Legit  white  
6494      9.4   Legit  white  
6495     12.8   Legit  white  
6496     11.8   Legit  white  

[6497 rows x 13 columns]

In [5]:
X = df.drop('quality',axis=1)
y = df['quality']

In [6]:
encoder = LabelEncoder() 
X['type'] = encoder.fit_transform(X['type'])

In [7]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  type  
0         9.4     0  
1         9.8     0  
2         9.8     0  
3         9.8     0  
4         9.4     0  
...       ...   ...  
6492     11.2     1  
6493      9.6     1  
6494      9.4     1  
6495     12.8     1  
6496     11.8     1  

[6497 rows x 12 columns]

## Feature Selection with Chi Square

In [8]:
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [9]:

# k = 4 tells four top features to be selected
# Score function Chi2 tells the feature to be selected using Chi Square
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, y)
fit.scores_

array([7.18727644e-01, 1.18552395e+01, 1.64369707e+00, 6.42180788e+01,
       1.69351768e-01, 4.86716943e+02, 2.22820658e+02, 1.57006382e-05,
       2.10960733e-02, 3.13841036e-01, 2.30356743e+00, 3.38064138e-02])

In [10]:
np.round_(fit.scores_)

array([  1.,  12.,   2.,  64.,   0., 487., 223.,   0.,   0.,   0.,   2.,
         0.])

In [11]:
chi = pd.Series(fit.scores_)
chi.index = X.columns
chi.sort_values(ascending=False)

free sulfur dioxide     486.716943
total sulfur dioxide    222.820658
residual sugar           64.218079
volatile acidity         11.855239
alcohol                   2.303567
citric acid               1.643697
fixed acidity             0.718728
sulphates                 0.313841
chlorides                 0.169352
type                      0.033806
pH                        0.021096
density                   0.000016
dtype: float64

In [12]:
X_new=test.fit_transform(X, y)

In [13]:
X_new

array([[  0.7 ,   1.9 ,  11.  ,  34.  ],
       [  0.88,   2.6 ,  25.  ,  67.  ],
       [  0.76,   2.3 ,  15.  ,  54.  ],
       ...,
       [  0.24,   1.2 ,  30.  , 111.  ],
       [  0.29,   1.1 ,  20.  , 110.  ],
       [  0.21,   0.8 ,  22.  ,  98.  ]])

more info : https://www.youtube.com/watch?v=6gHUIdGh2-Y

syarat menggunakaan chi square 
- dataset harus numerik semua
- no negative value
- categorical harus di label encoder terlebih dahulu
- hanya bisa digunakan untuk target yang categorical

## Feature Selection Mutual Info Classifiers

In [14]:
from sklearn.feature_selection import mutual_info_classif
# determine the mutual information
mutual_info = mutual_info_classif(X, y)
mutual_info

array([0.00163074, 0.00731763, 0.00561291, 0.00644239, 0.00230263,
       0.01721255, 0.00491598, 0.00153107, 0.00025582, 0.00153743,
       0.00084822, 0.00235766])

In [15]:
mutual_info = pd.Series(mutual_info)
mutual_info.index = X.columns
mutual_info.sort_values(ascending=False)

free sulfur dioxide     0.017213
volatile acidity        0.007318
residual sugar          0.006442
citric acid             0.005613
total sulfur dioxide    0.004916
type                    0.002358
chlorides               0.002303
fixed acidity           0.001631
sulphates               0.001537
density                 0.001531
alcohol                 0.000848
pH                      0.000256
dtype: float64

## Feature Selection Mutual Information for Regression

In [16]:
housing_df = pd.read_csv('./dataset/Ames_Housing_Data.csv')

In [17]:
housing_df.head()

PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley  \
0  526301100           20        RL         141.0     31770   Pave   NaN   
1  526350040           20        RH          80.0     11622   Pave   NaN   
2  526351010           20        RL          81.0     14267   Pave   NaN   
3  526353030           20        RL          93.0     11160   Pave   NaN   
4  527105010           60        RL          74.0     13830   Pave   NaN   

  Lot Shape Land Contour Utilities  ... Pool Area Pool QC  Fence Misc Feature  \
0       IR1          Lvl    AllPub  ...         0     NaN    NaN          NaN   
1       Reg          Lvl    AllPub  ...         0     NaN  MnPrv          NaN   
2       IR1          Lvl    AllPub  ...         0     NaN    NaN         Gar2   
3       Reg          Lvl    AllPub  ...         0     NaN    NaN          NaN   
4       IR1          Lvl    AllPub  ...         0     NaN  MnPrv          NaN   

  Misc Val Mo Sold Yr Sold  Sale Type  Sale Condition  SalePrice  
0        0       5    2010        WD           Normal     215000  
1        0       6    2010        WD           Normal     105000  
2    12500       6    2010        WD           Normal     172000  
3        0       4    2010        WD           Normal     244000  
4        0       3    2010        WD           Normal     189900  

[5 rows x 81 columns]

In [18]:
numerical_cols = housing_df.select_dtypes(include=np.number).columns.tolist()

In [19]:
housing_df=housing_df[numerical_cols]

In [20]:
housing_df=housing_df.drop("PID",axis=1)

In [21]:
X1 = housing_df.drop(labels=['SalePrice'], axis=1)
y1 = housing_df['SalePrice']

In [22]:
from sklearn.feature_selection import mutual_info_regression
mutual_info = mutual_info_regression(X1.fillna(0), y1)
mutual_info

array([0.28331433, 0.23883072, 0.16698672, 0.57154884, 0.13851676,
       0.39963818, 0.3048891 , 0.16529576, 0.17682374, 0.        ,
       0.11490516, 0.3922517 , 0.36918236, 0.21937225, 0.        ,
       0.49506876, 0.04287369, 0.02896271, 0.25152094, 0.07392191,
       0.0408695 , 0.00234362, 0.20490565, 0.16763507, 0.31731326,
       0.37745105, 0.41518539, 0.10709536, 0.17671441, 0.04660018,
       0.        , 0.00554619, 0.00989544, 0.00372124, 0.00089588,
       0.02953825])

In [23]:
mutual_info = pd.Series(mutual_info)
mutual_info.index = X1.columns
mutual_info.sort_values(ascending=False)

Overall Qual       0.571549
Gr Liv Area        0.495069
Garage Area        0.415185
Year Built         0.399638
Total Bsmt SF      0.392252
Garage Cars        0.377451
1st Flr SF         0.369182
Garage Yr Blt      0.317313
Year Remod/Add     0.304889
MS SubClass        0.283314
Full Bath          0.251521
Lot Frontage       0.238831
2nd Flr SF         0.219372
TotRms AbvGrd      0.204906
BsmtFin SF 1       0.176824
Open Porch SF      0.176714
Fireplaces         0.167635
Lot Area           0.166987
Mas Vnr Area       0.165296
Overall Cond       0.138517
Bsmt Unf SF        0.114905
Wood Deck SF       0.107095
Half Bath          0.073922
Enclosed Porch     0.046600
Bsmt Full Bath     0.042874
Bedroom AbvGr      0.040869
Yr Sold            0.029538
Bsmt Half Bath     0.028963
Pool Area          0.009895
Screen Porch       0.005546
Misc Val           0.003721
Kitchen AbvGr      0.002344
Mo Sold            0.000896
BsmtFin SF 2       0.000000
Low Qual Fin SF    0.000000
3Ssn Porch         0

## ANOVA f-test statistic

In [ ]:
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectKBest
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [ ]:
f_test = SelectKBest(score_func=f_classif, k=4)
fit = f_test.fit(X, y)
fit.scores_

array([3.08644096e+00, 1.52016610e+02, 2.48925411e+01, 1.54763350e+01,
       7.73964554e+00, 4.74970744e+01, 8.08158370e+00, 1.73699673e+00,
       2.62700596e+00, 7.53737820e+00, 1.70314036e+01, 1.37321639e-01])

In [ ]:
np.round_(fit.scores_)

array([  3., 152.,  25.,  15.,   8.,  47.,   8.,   2.,   3.,   8.,  17.,
         0.])

In [ ]:
result = pd.Series(fit.scores_)
result.index = X.columns
result.sort_values(ascending=False)

volatile acidity        152.016610
free sulfur dioxide      47.497074
citric acid              24.892541
alcohol                  17.031404
residual sugar           15.476335
total sulfur dioxide      8.081584
chlorides                 7.739646
sulphates                 7.537378
fixed acidity             3.086441
pH                        2.627006
density                   1.736997
type                      0.137322
dtype: float64

more info : https://machinelearningmastery.com/feature-selection-with-numerical-input-data/