In [2]:
import sympy as sy

In [3]:
x = sy.Symbol('x')

In [4]:
# 2x^2 + 4x - 1
y = 2*(x)**2 + 4*x - 1
display(y)

2*x**2 + 4*x - 1

In [5]:
y_=y.diff(x)
display(y_)

4*x + 4

In [6]:
display(y_.diff(x))

4

# Derivative

In [7]:
import numpy as np

In [8]:
x = np.linspace(0,20)
display(x)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [9]:
y = 2*x**2 + 4*x - 1
display(y)

array([ -1.        ,   0.96584756,   3.59808413,   6.8967097 ,
        10.86172428,  15.49312786,  20.79092045,  26.75510204,
        33.38567264,  40.68263224,  48.64598084,  57.27571845,
        66.57184506,  76.53436068,  87.16326531,  98.45855893,
       110.42024157, 123.0483132 , 136.34277384, 150.30362349,
       164.93086214, 180.2244898 , 196.18450646, 212.81091212,
       230.10370679, 248.06289046, 266.68846314, 285.98042482,
       305.93877551, 326.5635152 , 347.8546439 , 369.8121616 ,
       392.4360683 , 415.72636401, 439.68304873, 464.30612245,
       489.59558517, 515.5514369 , 542.17367763, 569.46230737,
       597.41732611, 626.03873386, 655.32653061, 685.28071637,
       715.90129113, 747.18825489, 779.14160766, 811.76134944,
       845.04748022, 879.        ])

In [10]:
df = np.diff(y)/np.diff(x)
display(df)

array([ 4.81632653,  6.44897959,  8.08163265,  9.71428571, 11.34693878,
       12.97959184, 14.6122449 , 16.24489796, 17.87755102, 19.51020408,
       21.14285714, 22.7755102 , 24.40816327, 26.04081633, 27.67346939,
       29.30612245, 30.93877551, 32.57142857, 34.20408163, 35.83673469,
       37.46938776, 39.10204082, 40.73469388, 42.36734694, 44.        ,
       45.63265306, 47.26530612, 48.89795918, 50.53061224, 52.16326531,
       53.79591837, 55.42857143, 57.06122449, 58.69387755, 60.32653061,
       61.95918367, 63.59183673, 65.2244898 , 66.85714286, 68.48979592,
       70.12244898, 71.75510204, 73.3877551 , 75.02040816, 76.65306122,
       78.28571429, 79.91836735, 81.55102041, 83.18367347])

In [11]:
display(np.gradient(y,x))

array([ 4.81632653,  5.63265306,  7.26530612,  8.89795918, 10.53061224,
       12.16326531, 13.79591837, 15.42857143, 17.06122449, 18.69387755,
       20.32653061, 21.95918367, 23.59183673, 25.2244898 , 26.85714286,
       28.48979592, 30.12244898, 31.75510204, 33.3877551 , 35.02040816,
       36.65306122, 38.28571429, 39.91836735, 41.55102041, 43.18367347,
       44.81632653, 46.44897959, 48.08163265, 49.71428571, 51.34693878,
       52.97959184, 54.6122449 , 56.24489796, 57.87755102, 59.51020408,
       61.14285714, 62.7755102 , 64.40816327, 66.04081633, 67.67346939,
       69.30612245, 70.93877551, 72.57142857, 74.20408163, 75.83673469,
       77.46938776, 79.10204082, 80.73469388, 82.36734694, 83.18367347])

# Partial Derivative

![partial derivative](./Screen%20Shot%202022-10-11%20at%2014.59.05.png)

In [12]:
x, y = sy.symbols(['x', 'y'])
f = x*(y)**2 + x**3
display(f)

x**3 + x*y**2

In [13]:
f_x = f.diff(x)
display(f_x)

3*x**2 + y**2

In [14]:
f_x_y = f_x.diff(y)
# 3x^2 + y^2
# |
# v
# (3x^2 * 0y^-1) + 2y == 2y
display(f_x_y)

2*y

# Jacobian

In [15]:
x, y = sy.symbols(['x', 'y'])
j = sy.Matrix([x**2*y+y,2*x*y-2])
display(j)

Matrix([
[x**2*y + y],
[ 2*x*y - 2]])

In [16]:
j.jacobian((x,y))

Matrix([
[2*x*y, x**2 + 1],
[  2*y,      2*x]])

# Hessian

In [17]:
x, y = sy.symbols(['x', 'y'])
eq = x*(y)**2 + x**3
eq

x**3 + x*y**2

In [18]:
sy.hessian(eq,(x,y))

Matrix([
[6*x, 2*y],
[2*y, 2*x]])