In [88]:
import numpy as np

reference: https://mathsolver.microsoft.com/id/solve-problem/%7B%20x%20%20%7D%5E%7B%202%20%20%7D%20%20-5x%2B10%20%3D%20%200
![persamaan kaudrat](./Screen%20Shot%202022-10-11%20at%2021.23.20.png)

reference: https://byjus.com/jee/normalized-and-decomposition-of-eigenvectors/#:~:text=Normalized%20eigenvector%20is%20nothing%20but,the%20vector%20of%20length%20one.
![normalized eigen vector](./Screen%20Shot%202022-10-11%20at%2021.34.31.png)

# Problems 1

Is `[1,3]` an eigen vector of `[[1,-1],[6,4]]`
```
λ = (A @ x) /  x
  = [-2]    / [1]
    [18]      [3]
  = [-2]
    [ 6]
  A    @  x       λ  *  x 
[1 -1] . [1]  = [-2] x [1]
[6  4]   [3]    [ 6]   [3]

         [-2] = [-2]
         [18]   [18]
```

Yes, `[1,3]` is an eigen vector of `[[1,-1],[6,4]]`

In [89]:
# Problems 1
A = np.array([[1,-1],
              [6, 4]])
x = np.array([1,3])
# A . x = λ * x
# λ     = A . x / x
λ = A @ x / x

print(A @ x == λ * x)

[ True  True]


# Playground

![contoh eigen vector](./Screen%20Shot%202022-10-11%20at%2022.14.37.png)

## Prove that np.linalg.eig return normalized vector

In [90]:
A = np.array([[1,2],[2,4]])
x = np.array([1,2])
eigvalues, eigvectors = np.linalg.eig(A)
display(eigvalues, eigvectors)

# normalized eigen vector = [ x1 / np.sqrt(x1^2 + x2^2 + ... +xn^2) ]
#                           [ x2 / np.sqrt(x1^2 + x2^2 + ... +xn^2) ]
#                           [ ...                                   ]
#                           [ xn / np.sqrt(x1^2 + x2^2 + ... +xn^2) ]
# reminder: np.linalg.eig return normalized eigen vector.
#                                     np.sqrt( 1 + 4 ) is just a quick way.
#           actual real life use cae: np.sqrt( np.ones( len(x) ) @ x**2 )
normalized_eigvector = x / np.sqrt(1+4)
display(normalized_eigvector)

# prove that np.linalg.eig return normalized eigen vector
np.array_equal(normalized_eigvector, np.absolute(eigvectors[1]))

array([0., 5.])

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

array([0.4472136 , 0.89442719])

True

## Prove the eigendecomposition formula

```
A.x           = λ * x
A.x           = λ.I * x
A.x - λ.Ix    = 0
(A - λ*I) @ x = 0
det(A - λ*I)  = 0
```

In [96]:
A = np.array([[1,2],[2,4]])
x = np.array([1,2])
λ = A @ x / x

# prove: A . x = λ.I * x
print(A @ x == λ @ np.identity(2) * x)

# prove: λ.Ix = λI.x
print(λ @ np.identity(2) * x)
print(λ * np.identity(2) @ x)

# prove: det(A - λ*I) = 0
# det([a b]) = a*d - b*c
#    ([c d])
print(A - λ*np.identity(2))
print(np.linalg.det(A - λ*np.identity(2))) # expected = 0

[ True  True]
[ 5. 10.]
[ 5. 10.]
[[-4.  2.]
 [ 2. -1.]]
0.0


In [92]:
A = np.array([[1,2],[2,4]])
x = np.array([1,2])

display(np.identity(2))

# prove: (A - λ*I) . x = 0
display(
    (A - (eigvalues[1] * np.identity(2))) @ np.array([1,2])
) # expected [0,0]

array([[1., 0.],
       [0., 1.]])

array([0., 0.])