In [4]:
import numpy as np

reference: https://mathsolver.microsoft.com/id/solve-problem/%7B%20x%20%20%7D%5E%7B%202%20%20%7D%20%20-5x%2B10%20%3D%20%200
![persamaan kaudrat](./Screen%20Shot%202022-10-11%20at%2021.23.20.png)

reference: https://byjus.com/jee/normalized-and-decomposition-of-eigenvectors/#:~:text=Normalized%20eigenvector%20is%20nothing%20but,the%20vector%20of%20length%20one.
![normalized eigen vector](./Screen%20Shot%202022-10-11%20at%2021.34.31.png)

In [14]:
# Problems 1
# Ax = lamda x
# [1 -1 [1  = lamda [ 1 ] 
#  6 4]  3]           3
A = np.array([[1,-1],[6,4]])
eigvalues, eigvectors = np.linalg.eig(A)
display(eigvalues, eigvectors)
display(eigvectors[0]*np.sqrt(eigvalues[0]))
display(eigvectors[1]*np.sqrt(eigvalues[1]))

# jawabannya bukan.
# tapi bagaimana cara membandingkan normalized eigen vector dengan eigen vector ya?

array([2.5+1.93649167j, 2.5-1.93649167j])

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

array([-0.56139353+0.36958255j, -0.21749838-0.63596258j])

array([1.55778382-0.53276006j, 1.55778382-0.53276006j])