In [37]:
import numpy as np

reference: https://mathsolver.microsoft.com/id/solve-problem/%7B%20x%20%20%7D%5E%7B%202%20%20%7D%20%20-5x%2B10%20%3D%20%200
![persamaan kaudrat](./Screen%20Shot%202022-10-11%20at%2021.23.20.png)

reference: https://byjus.com/jee/normalized-and-decomposition-of-eigenvectors/#:~:text=Normalized%20eigenvector%20is%20nothing%20but,the%20vector%20of%20length%20one.
![normalized eigen vector](./Screen%20Shot%202022-10-11%20at%2021.34.31.png)

In [38]:
# Problems 1
# Ax = lamda x
# [1 -1 [1  = lamda [ 1 ] 
#  6 4]  3]           3
A = np.array([[1,-1],[6,4]])
display(A)
eigvalues, eigvectors = np.linalg.eig(A)

normalized_eigvector = np.array([1,3]) * np.sqrt(1 + 9)

eigvector_absolute = np.absolute(eigvectors[0])
display(np.array_equal(normalized_eigvector, eigvector_absolute))
eigvector_absolute = np.absolute(eigvectors[1])
display(np.array_equal(normalized_eigvector, eigvector_absolute))

# jawabannya bukan.
# apa ini cara membandingkan normalized eigvector dengan eigvector?

array([[ 1, -1],
       [ 6,  4]])

False

False

# Playground

![contoh eigen vector](./Screen%20Shot%202022-10-11%20at%2022.14.37.png)

In [39]:
A = np.array([[1,2],[2,4]])
eigvalues, eigvectors = np.linalg.eig(A)
display(eigvalues, eigvectors)

normalized_eigvector = np.array([1,2]) / np.sqrt(1+4)

eigvector_absolute = np.absolute(eigvectors[1])

np.array_equal(normalized_eigvector, eigvector_absolute)

array([0., 5.])

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

True