In [59]:
# Import Library
import numpy as np

In [60]:
# Pendefinisian Array
a = [1,2,3]
vect_a = np.array(a)

In [61]:
# Operasi Aritmatika dengan Bilangan

display(vect_a + 2)
display(vect_a - 2)
display(vect_a / 2)

array([3, 4, 5])

array([-1,  0,  1])

array([0.5, 1. , 1.5])

In [62]:
# Operasi Aritmatika dengan Vector

# tensorflow -> tensor -> 3D
# vector -> 1D [1,2,3]
# matrix -> 2D [[1,2,3],[4,5,6]]
# tensor -> 3D

# vector?
# ->          ->
# a = ( 1 ) ; a + 2 = ( 1 + 2 ) = ( 3 )
#     ( 2 )           ( 2 + 2 )   ( 4 )
#     ( 3 )           ( 3 + 2 )   ( 5 )
# ->          ->  ->
# b = ( 4 ) ; a + b = ( 1 + 4 ) = ( 5 )
#     ( 5 )           ( 2 + 5 )   ( 7 )
#     ( 6 )           ( 3 + 6 )   ( 9 )

vect_b = np.array([4,5,6])

display("dengan vector",vect_a + vect_b)
display("dengan vector", vect_a - vect_b)
display("element wise", vect_a / vect_b)
display("element wise", vect_a * vect_b)
# dot product
# tidak dimutlakkan, jadi jika vector memiliki angka negatif, hasilnya akan negatif.
display("dot product", vect_a.dot(vect_b))

'dengan vector'

array([5, 7, 9])

'dengan vector'

array([-3, -3, -3])

'element wise'

array([0.25, 0.4 , 0.5 ])

'element wise'

array([ 4, 10, 18])

'dot product'

32

In [63]:
# L1 - manhattan distance
# ||u|| = |u1| + |u2| + ... + |un|
# L2 - euclidean distance
# ||u|| = √(u1^2 + u2^2 + ... + un^2)
# ||u|| -> disebut sebagai Vector Norm u.

In [64]:
# Mencari Vector Norm
d = [8,6]
vect_d = np.array(d)
print('L1 - Manhattan Distance', np.linalg.norm(vect_d, 1))
print('L2 - Euclidean Distance', np.linalg.norm(vect_d)) # ord = 2

L1 - Manhattan Distance 14.0
L2 - Euclidean Distance 10.0


In [65]:
# Operasi Perkalian dengan Bilangan

e = [1,2,3]
vect_e = np.array(e)

display(vect_e * 2)

array([2, 4, 6])

In [66]:
# Operasi Perkalian dengan Sesama Vector (Element Wise)

f = [1,2,3]
g = [4,5,6]

vect_f = np.array(f)
vect_g = np.array(g)

display('Hasil Perkalian - Element Wise',vect_f * vect_g)
# dot product sama seperti vector_f * vect_g, kemudian dijumlahkan
# tapi angkanya tidak dimutlakkan sehingga hasilnya dapat negatif.
display('Hasil Perkalian - Dot Product',
    vect_f @ vect_g,
    vect_f.dot(vect_g),
    np.dot(vect_f, vect_g))

'Hasil Perkalian - Element Wise'

array([ 4, 10, 18])

'Hasil Perkalian - Dot Product'

32

32

32

![cosline similarity](./Screen%20Shot%202022-10-10%20at%2014.40.21.png)
![cos theta](./Screen%20Shot%202022-10-10%20at%2014.45.15.png)

In [67]:
# Cosline similarity

k = [8,0]
m = [6,2]

vect_k = np.array(k)
vect_m = np.array(m)

cos_theta = (vect_k @ vect_m) / (np.linalg.norm(vect_k) * np.linalg.norm(vect_m))
cos_theta # expected output: >= 0.8 == similiar vector
# cos_theta == ini cosine similarity

0.9486832980505138

In [68]:
# Mencari radian dan degree

# cosine similarity
# |
# v
# radian ( 0 - 2pi )
# |
# v
# sudut ( 0 - 360 derajat )

radian = np.arccos(cos_theta)
degree = np.degrees(radian)
print('Radian: ', radian)
print('Degree: ', degree)

Radian:  0.3217505543966423
Degree:  18.434948822922017


# text similarity

## metode: term frequency

kelemahan -> ga bisa membedakan positioning text `kucing mengejar tikus`, `tikus mengejar kucing`

![disadvantage](./Screen%20Shot%202022-10-10%20at%2015.05.32.png)

### studi kasus

teks_1 = "saya pergi ke rumah kakak saya"

teks_2 = "saya perrgi ke rumah nenek saya"

![text similarity](./Screen%20Shot%202022-10-10%20at%2015.02.03.png)

In [69]:
# Pendefinisian Vector

t1 = [2,1,1,1,1,0]
t2 = [2,1,1,1,0,1]

vect_t1 = np.array(t1)
vect_t2 = np.array(t2)

cos_theta = (vect_t1 @ vect_t2) / (np.linalg.norm(vect_t1) * np.linalg.norm(vect_t2))
cos_theta

0.8749999999999998

## Matrix

In [70]:
# Pendefinisian Matrix

A = [[1,2,3],
     [4,5,6]]

matrix_A = np.array(A)
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
matrix_A.shape # (2,3) -> 2 baris, 3 kolom

(2, 3)

In [72]:
# Operasi Aritmatika terhadap Matrix dengan Bilangan
print(matrix_A + 2)
print(matrix_A - 2)
print(matrix_A * 2)
print(matrix_A / 2)

[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [73]:
# Pendefinisian Matrix B

B = [[7,8,9],
     [10,11,12]]

matrix_B = np.array(B)
matrix_B

array([[ 7,  8,  9],
       [10, 11, 12]])

In [74]:
# Operasi Aritmatika Antar Sesama Matrix

print("matrix_A", matrix_A, "\nmatrix_B", matrix_B)
print("+", matrix_A + matrix_B)
print("-",matrix_A - matrix_B)
print("*",matrix_A * matrix_B)
print("/",matrix_A / matrix_B)

matrix_A [[1 2 3]
 [4 5 6]] 
matrix_B [[ 7  8  9]
 [10 11 12]]
+ [[ 8 10 12]
 [14 16 18]]
- [[-6 -6 -6]
 [-6 -6 -6]]
* [[ 7 16 27]
 [40 55 72]]
/ [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


#### Matrix Multiplication

![matrix multiplication](./Screen%20Shot%202022-10-10%20at%2015.19.50.png)

In [75]:
# Perkalian Vector (Matrix Multiplication)

A = [[1,2],
     [3,4],
     [5,6]]

B = [[1,2],
     [3,4]]

matrix_A = np.array(A)
matrix_B = np.array(B)

print(matrix_A @ matrix_B)

[[ 7 10]
 [15 22]
 [23 34]]


```
Matrix @ ? == Matrix itu sendiri
         ? == Identitas.
```

![pembuktian matrix identitas](./Screen%20Shot%202022-10-10%20at%2015.29.14.png)

In [76]:
# Pembuktian Matrix Identitas

C = [[1,2,3],
     [4,5,6],
     [7,8,9]]

matrix_C = np.array(C)
print(matrix_C)

matrix_D = np.eye(3,3)
print(matrix_D)

print(matrix_C @ matrix_D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
