In [4]:
import numpy as np

In [15]:
# Problems 1 (di soal matrix, tapi mintanya tensor)
tensor_A = np.array([
    [[23,50], [7,12]],
    [[57,67], [99,43]],
    [[75,21], [57,12]],
    [[87,26], [18,84]]
])
tensor_A

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [22]:
# Problems 2

matrix_A = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98]
])
display(matrix_A)
matrix_B = np.array([
    [17],
    [22],
    [19]
])
display(matrix_B)
display(matrix_A * matrix_B)

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

array([[17],
       [22],
       [19]])

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

In [30]:
# Problems 3 (determinant A, inverse A untuk apa ya?)
matrix_A = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98]
])
display("A", matrix_A)
display("A.T", matrix_A.T)
display("determinant A",np.linalg.det(matrix_A))
display("inverse A", np.linalg.inv(matrix_A))

'A'

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

'A.T'

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

'determinant A'

131344.0000000002

'inverse A'

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])